#!/bin/bash

abc() { # $("comment")
  bar="foo"
  echo "
  $(echo \
    "$(echo '$()' "\"" "${bar}")" \
    `echo $(echo \`echo "a"\`)`
  )"
  d="{\"x\":\"xxx\"}"

  def()

  {
   echo def
  }
}

{
  ghi(){
    echo ghi
  }
}

abc
def
ghi
# comment and "", ''
' #' # ''
" #
" # ""
${#} " "
$#   " "
